// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cliente.sql

package dto

import (
	"context"
	"database/sql"
)

const createCliente = `-- name: CreateCliente :execresult
INSERT INTO Cliente (
    cedula,
    idTipoCliente,
    nombre,
    apellidos,
    telefono,
    direccion
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateClienteParams struct {
	Cedula        string `json:"cedula"`
	Idtipocliente int32  `json:"idtipocliente"`
	Nombre        string `json:"nombre"`
	Apellidos     string `json:"apellidos"`
	Telefono      string `json:"telefono"`
	Direccion     string `json:"direccion"`
}

func (q *Queries) CreateCliente(ctx context.Context, arg CreateClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCliente,
		arg.Cedula,
		arg.Idtipocliente,
		arg.Nombre,
		arg.Apellidos,
		arg.Telefono,
		arg.Direccion,
	)
}

const deleteCliente = `-- name: DeleteCliente :execresult
UPDATE Cliente
SET estado = 0
WHERE cedula = ?
`

func (q *Queries) DeleteCliente(ctx context.Context, cedula string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCliente, cedula)
}

const getClienteByCedula = `-- name: GetClienteByCedula :one
SELECT
    cedula,
    idTipoCliente,
    nombre,
    apellidos,
    telefono,
    direccion,
    estado
FROM Cliente
WHERE cedula = ?
`

func (q *Queries) GetClienteByCedula(ctx context.Context, cedula string) (Cliente, error) {
	row := q.db.QueryRowContext(ctx, getClienteByCedula, cedula)
	var i Cliente
	err := row.Scan(
		&i.Cedula,
		&i.Idtipocliente,
		&i.Nombre,
		&i.Apellidos,
		&i.Telefono,
		&i.Direccion,
		&i.Estado,
	)
	return i, err
}

const getClientes = `-- name: GetClientes :many
SELECT
    cedula,
    idTipoCliente,
    nombre,
    apellidos,
    telefono,
    direccion,
    estado
FROM Cliente
`

func (q *Queries) GetClientes(ctx context.Context) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, getClientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.Cedula,
			&i.Idtipocliente,
			&i.Nombre,
			&i.Apellidos,
			&i.Telefono,
			&i.Direccion,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClientesByTipoCliente = `-- name: GetClientesByTipoCliente :many
SELECT
    cedula,
    idTipoCliente,
    nombre,
    apellidos,
    telefono,
    direccion,
    estado
FROM Cliente
WHERE idTipoCliente = ?
`

func (q *Queries) GetClientesByTipoCliente(ctx context.Context, idtipocliente int32) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, getClientesByTipoCliente, idtipocliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.Cedula,
			&i.Idtipocliente,
			&i.Nombre,
			&i.Apellidos,
			&i.Telefono,
			&i.Direccion,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClientes = `-- name: SearchClientes :many
SELECT
    cedula,
    idTipoCliente,
    nombre,
    apellidos,
    telefono,
    direccion,
    estado
FROM Cliente
WHERE
    CAST(cedula AS CHAR) LIKE CONCAT(?, '%')
    OR nombre LIKE CONCAT(?, '%')
    OR apellidos LIKE CONCAT(?, '%')
    OR telefono LIKE CONCAT(?, '%')
    OR direccion LIKE CONCAT(?, '%')
`

type SearchClientesParams struct {
	CONCAT   interface{} `json:"CONCAT"`
	CONCAT_2 interface{} `json:"CONCAT_2"`
	CONCAT_3 interface{} `json:"CONCAT_3"`
	CONCAT_4 interface{} `json:"CONCAT_4"`
	CONCAT_5 interface{} `json:"CONCAT_5"`
}

func (q *Queries) SearchClientes(ctx context.Context, arg SearchClientesParams) ([]Cliente, error) {
	rows, err := q.db.QueryContext(ctx, searchClientes,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.CONCAT_3,
		arg.CONCAT_4,
		arg.CONCAT_5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cliente
	for rows.Next() {
		var i Cliente
		if err := rows.Scan(
			&i.Cedula,
			&i.Idtipocliente,
			&i.Nombre,
			&i.Apellidos,
			&i.Telefono,
			&i.Direccion,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleClienteEstado = `-- name: ToggleClienteEstado :execresult
UPDATE Cliente
SET estado = NOT estado
WHERE cedula = ?
`

func (q *Queries) ToggleClienteEstado(ctx context.Context, cedula string) (sql.Result, error) {
	return q.db.ExecContext(ctx, toggleClienteEstado, cedula)
}

const updateCliente = `-- name: UpdateCliente :execresult
UPDATE Cliente
SET
    idTipoCliente = ?,
    nombre = ?,
    apellidos = ?,
    telefono = ?,
    direccion = ?,
    estado = ?
WHERE cedula = ?
`

type UpdateClienteParams struct {
	Idtipocliente int32  `json:"idtipocliente"`
	Nombre        string `json:"nombre"`
	Apellidos     string `json:"apellidos"`
	Telefono      string `json:"telefono"`
	Direccion     string `json:"direccion"`
	Estado        int8   `json:"estado"`
	Cedula        string `json:"cedula"`
}

func (q *Queries) UpdateCliente(ctx context.Context, arg UpdateClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCliente,
		arg.Idtipocliente,
		arg.Nombre,
		arg.Apellidos,
		arg.Telefono,
		arg.Direccion,
		arg.Estado,
		arg.Cedula,
	)
}
