// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: detalleReserva.sql

package dto

import (
	"context"
	"database/sql"
	"time"

	decimal "github.com/shopspring/decimal"
)

const countTraslapesDetalleReserva = `-- name: CountTraslapesDetalleReserva :one
SELECT COUNT(*)
FROM detallereserva
WHERE idHabitacion = ?
  AND fechaEntrada < ?
  AND fechaSalida > ?
`

type CountTraslapesDetalleReservaParams struct {
	Idhabitacion int32     `json:"idhabitacion"`
	Fechasalida  time.Time `json:"fechasalida"`
	Fechaentrada time.Time `json:"fechaentrada"`
}

func (q *Queries) CountTraslapesDetalleReserva(ctx context.Context, arg CountTraslapesDetalleReservaParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTraslapesDetalleReserva, arg.Idhabitacion, arg.Fechasalida, arg.Fechaentrada)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTraslapesDetalleReservaUpdate = `-- name: CountTraslapesDetalleReservaUpdate :one
SELECT COUNT(*)
FROM detallereserva
WHERE idHabitacion = ?
  AND idDetalleReserva <> ?
  AND fechaEntrada < ?
  AND fechaSalida > ?
`

type CountTraslapesDetalleReservaUpdateParams struct {
	Idhabitacion     int32     `json:"idhabitacion"`
	Iddetallereserva int32     `json:"iddetallereserva"`
	Fechasalida      time.Time `json:"fechasalida"`
	Fechaentrada     time.Time `json:"fechaentrada"`
}

func (q *Queries) CountTraslapesDetalleReservaUpdate(ctx context.Context, arg CountTraslapesDetalleReservaUpdateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTraslapesDetalleReservaUpdate,
		arg.Idhabitacion,
		arg.Iddetallereserva,
		arg.Fechasalida,
		arg.Fechaentrada,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDetalleReserva = `-- name: CreateDetalleReserva :execresult
INSERT INTO detallereserva (idHabitacion, idReserva, idTarifa,cantidadPersonas,
                            precioAplicado,fechaEntrada,fechaSalida,iva,subTotal,total)
                            VALUES (?, ?, ?, ?,?,?,?,?,?,?)
`

type CreateDetalleReservaParams struct {
	Idhabitacion     int32           `json:"idhabitacion"`
	Idreserva        int32           `json:"idreserva"`
	Idtarifa         int32           `json:"idtarifa"`
	Cantidadpersonas int32           `json:"cantidadpersonas"`
	Precioaplicado   decimal.Decimal `json:"precioaplicado"`
	Fechaentrada     time.Time       `json:"fechaentrada"`
	Fechasalida      time.Time       `json:"fechasalida"`
	Iva              decimal.Decimal `json:"iva"`
	Subtotal         decimal.Decimal `json:"subtotal"`
	Total            decimal.Decimal `json:"total"`
}

func (q *Queries) CreateDetalleReserva(ctx context.Context, arg CreateDetalleReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createDetalleReserva,
		arg.Idhabitacion,
		arg.Idreserva,
		arg.Idtarifa,
		arg.Cantidadpersonas,
		arg.Precioaplicado,
		arg.Fechaentrada,
		arg.Fechasalida,
		arg.Iva,
		arg.Subtotal,
		arg.Total,
	)
}

const deleteDetalleReserva = `-- name: DeleteDetalleReserva :execresult
UPDATE detallereserva
SET estado = CASE
    WHEN estado = 1 THEN 0
    ELSE 1
END
WHERE idDetalleReserva= ?
`

func (q *Queries) DeleteDetalleReserva(ctx context.Context, iddetallereserva int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDetalleReserva, iddetallereserva)
}

const getAllDetalleReserva = `-- name: GetAllDetalleReserva :many
SELECT
    dr.idDetalleReserva,

    -- Datos de habitación
    th.nombreTipoHab AS nombreTipoHabitacion,
    h.numeroHabitacion,

    -- Datos de reserva
    CONCAT(rp.nombre, ' ', rp.apellidos) AS nombreRecepcionista,
    CONCAT(c.nombre, ' ', c.apellidos) AS nombreCliente,
    tc.nombreTipoC AS nombreTipoCliente,
    r.fechaReserva,
    r.estadoReserva,

    -- Datos de tarifa
    t.nombreTarifa,

    -- Campos propios de detalleReserva, sin FK
    dr.cantidadPersonas,
    dr.precioAplicado,
    dr.fechaEntrada,
    dr.fechaSalida,
    dr.iva,
    dr.subTotal,
    dr.total,
    dr.estado

FROM detallereserva dr
INNER JOIN habitacion h
    ON dr.idHabitacion = h.idHabitacion
INNER JOIN tipohabitacion th
    ON h.idTipoHab = th.idTipoHabitacion
INNER JOIN reserva r
    ON dr.idReserva = r.idReserva
INNER JOIN recepcionista rp
    ON r.idRecepcionista = rp.cedula
INNER JOIN cliente c
    ON r.idCliente = c.cedula
INNER JOIN tipocliente tc
    ON c.idTipoCliente = tc.idTipoCliente
INNER JOIN tarifa t
    ON dr.idTarifa = t.idTarifa
`

type GetAllDetalleReservaRow struct {
	Iddetallereserva     int32           `json:"iddetallereserva"`
	Nombretipohabitacion string          `json:"nombretipohabitacion"`
	Numerohabitacion     string          `json:"numerohabitacion"`
	Nombrerecepcionista  string          `json:"nombrerecepcionista"`
	Nombrecliente        string          `json:"nombrecliente"`
	Nombretipocliente    string          `json:"nombretipocliente"`
	Fechareserva         time.Time       `json:"fechareserva"`
	Estadoreserva        string          `json:"estadoreserva"`
	Nombretarifa         string          `json:"nombretarifa"`
	Cantidadpersonas     int32           `json:"cantidadpersonas"`
	Precioaplicado       decimal.Decimal `json:"precioaplicado"`
	Fechaentrada         time.Time       `json:"fechaentrada"`
	Fechasalida          time.Time       `json:"fechasalida"`
	Iva                  decimal.Decimal `json:"iva"`
	Subtotal             decimal.Decimal `json:"subtotal"`
	Total                decimal.Decimal `json:"total"`
	Estado               int8            `json:"estado"`
}

func (q *Queries) GetAllDetalleReserva(ctx context.Context) ([]GetAllDetalleReservaRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllDetalleReserva)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDetalleReservaRow
	for rows.Next() {
		var i GetAllDetalleReservaRow
		if err := rows.Scan(
			&i.Iddetallereserva,
			&i.Nombretipohabitacion,
			&i.Numerohabitacion,
			&i.Nombrerecepcionista,
			&i.Nombrecliente,
			&i.Nombretipocliente,
			&i.Fechareserva,
			&i.Estadoreserva,
			&i.Nombretarifa,
			&i.Cantidadpersonas,
			&i.Precioaplicado,
			&i.Fechaentrada,
			&i.Fechasalida,
			&i.Iva,
			&i.Subtotal,
			&i.Total,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClienteByReserva = `-- name: GetClienteByReserva :one
SELECT 
    tc.descuentoBase
FROM reserva r
INNER JOIN cliente c
    ON r.idCliente = c.cedula
INNER JOIN tipocliente tc
    ON c.idTipoCliente = tc.idTipoCliente
WHERE r.idReserva = ?
`

func (q *Queries) GetClienteByReserva(ctx context.Context, idreserva int32) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, getClienteByReserva, idreserva)
	var descuentobase decimal.Decimal
	err := row.Scan(&descuentobase)
	return descuentobase, err
}

const getDetalleReservaByID = `-- name: GetDetalleReservaByID :one
SELECT
    dr.idDetalleReserva,

    -- Datos de habitación
    th.nombreTipoHab AS nombreTipoHabitacion,
    h.numeroHabitacion,

    -- Datos de reserva
    CONCAT(rp.nombre, ' ', rp.apellidos) AS nombreRecepcionista,
    CONCAT(c.nombre, ' ', c.apellidos) AS nombreCliente,
    tc.nombreTipoC AS nombreTipoCliente,
    r.fechaReserva,
    r.estadoReserva,

    -- Datos de tarifa
    t.nombreTarifa,

    -- Campos de detalleReserva
    dr.cantidadPersonas,
    dr.precioAplicado,
    dr.fechaEntrada,
    dr.fechaSalida,
    dr.iva,
    dr.subTotal,
    dr.total,
    dr.estado

FROM detallereserva dr
INNER JOIN habitacion h
    ON dr.idHabitacion = h.idHabitacion
INNER JOIN tipohabitacion th
    ON h.idTipoHab = th.idTipoHabitacion
INNER JOIN reserva r
    ON dr.idReserva = r.idReserva
INNER JOIN recepcionista rp
    ON r.idRecepcionista = rp.cedula
INNER JOIN cliente c
    ON r.idCliente = c.cedula
INNER JOIN tipocliente tc
    ON c.idTipoCliente = tc.idTipoCliente
INNER JOIN tarifa t
    ON dr.idTarifa = t.idTarifa
WHERE dr.idDetalleReserva = ?
`

type GetDetalleReservaByIDRow struct {
	Iddetallereserva     int32           `json:"iddetallereserva"`
	Nombretipohabitacion string          `json:"nombretipohabitacion"`
	Numerohabitacion     string          `json:"numerohabitacion"`
	Nombrerecepcionista  string          `json:"nombrerecepcionista"`
	Nombrecliente        string          `json:"nombrecliente"`
	Nombretipocliente    string          `json:"nombretipocliente"`
	Fechareserva         time.Time       `json:"fechareserva"`
	Estadoreserva        string          `json:"estadoreserva"`
	Nombretarifa         string          `json:"nombretarifa"`
	Cantidadpersonas     int32           `json:"cantidadpersonas"`
	Precioaplicado       decimal.Decimal `json:"precioaplicado"`
	Fechaentrada         time.Time       `json:"fechaentrada"`
	Fechasalida          time.Time       `json:"fechasalida"`
	Iva                  decimal.Decimal `json:"iva"`
	Subtotal             decimal.Decimal `json:"subtotal"`
	Total                decimal.Decimal `json:"total"`
	Estado               int8            `json:"estado"`
}

func (q *Queries) GetDetalleReservaByID(ctx context.Context, iddetallereserva int32) (GetDetalleReservaByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDetalleReservaByID, iddetallereserva)
	var i GetDetalleReservaByIDRow
	err := row.Scan(
		&i.Iddetallereserva,
		&i.Nombretipohabitacion,
		&i.Numerohabitacion,
		&i.Nombrerecepcionista,
		&i.Nombrecliente,
		&i.Nombretipocliente,
		&i.Fechareserva,
		&i.Estadoreserva,
		&i.Nombretarifa,
		&i.Cantidadpersonas,
		&i.Precioaplicado,
		&i.Fechaentrada,
		&i.Fechasalida,
		&i.Iva,
		&i.Subtotal,
		&i.Total,
		&i.Estado,
	)
	return i, err
}

const getDetallesByReserva = `-- name: GetDetallesByReserva :many
SELECT
    dr.idDetalleReserva,
    th.nombreTipoHab AS nombreTipoHabitacion,
    h.numeroHabitacion,
    t.nombreTarifa,
    tc.descuentoBase,
    dr.cantidadPersonas,
    dr.precioAplicado,
    dr.fechaEntrada,
    dr.fechaSalida,
    dr.iva,
    dr.subTotal,
    dr.total,
    dr.estado
FROM detallereserva dr
INNER JOIN habitacion h ON dr.idHabitacion = h.idHabitacion
INNER JOIN tipohabitacion th ON h.idTipoHab = th.idTipoHabitacion
INNER JOIN tarifa t ON dr.idTarifa = t.idTarifa
INNER JOIN reserva r ON dr.idReserva = r.idReserva
INNER JOIN cliente c ON r.idCliente = c.cedula
INNER JOIN tipocliente tc ON c.idTipoCliente = tc.idTipoCliente
WHERE dr.idReserva = ? AND dr.estado = 1
`

type GetDetallesByReservaRow struct {
	Iddetallereserva     int32           `json:"iddetallereserva"`
	Nombretipohabitacion string          `json:"nombretipohabitacion"`
	Numerohabitacion     string          `json:"numerohabitacion"`
	Nombretarifa         string          `json:"nombretarifa"`
	Descuentobase        decimal.Decimal `json:"descuentobase"`
	Cantidadpersonas     int32           `json:"cantidadpersonas"`
	Precioaplicado       decimal.Decimal `json:"precioaplicado"`
	Fechaentrada         time.Time       `json:"fechaentrada"`
	Fechasalida          time.Time       `json:"fechasalida"`
	Iva                  decimal.Decimal `json:"iva"`
	Subtotal             decimal.Decimal `json:"subtotal"`
	Total                decimal.Decimal `json:"total"`
	Estado               int8            `json:"estado"`
}

func (q *Queries) GetDetallesByReserva(ctx context.Context, idreserva int32) ([]GetDetallesByReservaRow, error) {
	rows, err := q.db.QueryContext(ctx, getDetallesByReserva, idreserva)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetallesByReservaRow
	for rows.Next() {
		var i GetDetallesByReservaRow
		if err := rows.Scan(
			&i.Iddetallereserva,
			&i.Nombretipohabitacion,
			&i.Numerohabitacion,
			&i.Nombretarifa,
			&i.Descuentobase,
			&i.Cantidadpersonas,
			&i.Precioaplicado,
			&i.Fechaentrada,
			&i.Fechasalida,
			&i.Iva,
			&i.Subtotal,
			&i.Total,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEstadoDetalleReserva = `-- name: GetEstadoDetalleReserva :one
SELECT estado
FROM detalleReserva 
WHERE idDetalleReserva = ?
`

func (q *Queries) GetEstadoDetalleReserva(ctx context.Context, iddetallereserva int32) (int8, error) {
	row := q.db.QueryRowContext(ctx, getEstadoDetalleReserva, iddetallereserva)
	var estado int8
	err := row.Scan(&estado)
	return estado, err
}

const getFechasByIdDetalleReserva = `-- name: GetFechasByIdDetalleReserva :one
SELECT fechaEntrada,fechaSalida
FROM detallereserva
WHERE idDetalleReserva = ? AND estado = 1
`

type GetFechasByIdDetalleReservaRow struct {
	Fechaentrada time.Time `json:"fechaentrada"`
	Fechasalida  time.Time `json:"fechasalida"`
}

func (q *Queries) GetFechasByIdDetalleReserva(ctx context.Context, iddetallereserva int32) (GetFechasByIdDetalleReservaRow, error) {
	row := q.db.QueryRowContext(ctx, getFechasByIdDetalleReserva, iddetallereserva)
	var i GetFechasByIdDetalleReservaRow
	err := row.Scan(&i.Fechaentrada, &i.Fechasalida)
	return i, err
}

const getFechasOcupadasByHabitacion = `-- name: GetFechasOcupadasByHabitacion :many
SELECT fechaEntrada, fechaSalida
FROM detallereserva
WHERE idHabitacion = ? AND estado = 1
`

type GetFechasOcupadasByHabitacionRow struct {
	Fechaentrada time.Time `json:"fechaentrada"`
	Fechasalida  time.Time `json:"fechasalida"`
}

func (q *Queries) GetFechasOcupadasByHabitacion(ctx context.Context, idhabitacion int32) ([]GetFechasOcupadasByHabitacionRow, error) {
	rows, err := q.db.QueryContext(ctx, getFechasOcupadasByHabitacion, idhabitacion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFechasOcupadasByHabitacionRow
	for rows.Next() {
		var i GetFechasOcupadasByHabitacionRow
		if err := rows.Scan(&i.Fechaentrada, &i.Fechasalida); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservanByIdDetalleReserva = `-- name: GetReservanByIdDetalleReserva :one
SELECT idReserva
FROM detallereserva
WHERE idDetalleReserva = ? AND estado = 1
`

func (q *Queries) GetReservanByIdDetalleReserva(ctx context.Context, iddetallereserva int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getReservanByIdDetalleReserva, iddetallereserva)
	var idreserva int32
	err := row.Scan(&idreserva)
	return idreserva, err
}

const getTarifaActivaByTipoHabitacionAndFecha = `-- name: GetTarifaActivaByTipoHabitacionAndFecha :one
SELECT idTarifa, precioBase, nombreTarifa
FROM tarifa
WHERE idTipoHabitacion = ?
  AND estado = 1
  AND (
        (fechaInicio IS NULL AND fechaFin IS NULL)
        OR
        (CAST(? AS DATE) BETWEEN fechaInicio AND fechaFin)
      )
ORDER BY 
    CASE 
        WHEN fechaInicio IS NOT NULL AND fechaFin IS NOT NULL THEN 1
        ELSE 2
    END
LIMIT 1
`

type GetTarifaActivaByTipoHabitacionAndFechaParams struct {
	Idtipohabitacion int32     `json:"idtipohabitacion"`
	Fecha            time.Time `json:"fecha"`
}

type GetTarifaActivaByTipoHabitacionAndFechaRow struct {
	Idtarifa     int32           `json:"idtarifa"`
	Preciobase   decimal.Decimal `json:"preciobase"`
	Nombretarifa string          `json:"nombretarifa"`
}

func (q *Queries) GetTarifaActivaByTipoHabitacionAndFecha(ctx context.Context, arg GetTarifaActivaByTipoHabitacionAndFechaParams) (GetTarifaActivaByTipoHabitacionAndFechaRow, error) {
	row := q.db.QueryRowContext(ctx, getTarifaActivaByTipoHabitacionAndFecha, arg.Idtipohabitacion, arg.Fecha)
	var i GetTarifaActivaByTipoHabitacionAndFechaRow
	err := row.Scan(&i.Idtarifa, &i.Preciobase, &i.Nombretarifa)
	return i, err
}

const getTipoHabitacionByHabitacion = `-- name: GetTipoHabitacionByHabitacion :one
SELECT idTipoHab
FROM habitacion
WHERE idHabitacion = ? AND estado = 1
`

func (q *Queries) GetTipoHabitacionByHabitacion(ctx context.Context, idhabitacion int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getTipoHabitacionByHabitacion, idhabitacion)
	var idtipohab int32
	err := row.Scan(&idtipohab)
	return idtipohab, err
}

const updateDetalleReserva = `-- name: UpdateDetalleReserva :execresult
UPDATE detallereserva
SET
    idHabitacion = ?,
    idTarifa = ?,
    cantidadPersonas      = ?,
    precioAplicado      = ?,
    fechaEntrada     =COALESCE(?,fechaEntrada),
    fechaSalida      = COALESCE(?, fechaSalida),
    iva     = ?,
    subTotal      = ?,
    total      =?
WHERE idDetalleReserva = ?
`

type UpdateDetalleReservaParams struct {
	Idhabitacion     int32           `json:"idhabitacion"`
	Idtarifa         int32           `json:"idtarifa"`
	Cantidadpersonas int32           `json:"cantidadpersonas"`
	Precioaplicado   decimal.Decimal `json:"precioaplicado"`
	Fechaentrada     sql.NullTime    `json:"fechaentrada"`
	Fechasalida      sql.NullTime    `json:"fechasalida"`
	Iva              decimal.Decimal `json:"iva"`
	Subtotal         decimal.Decimal `json:"subtotal"`
	Total            decimal.Decimal `json:"total"`
	Iddetallereserva int32           `json:"iddetallereserva"`
}

func (q *Queries) UpdateDetalleReserva(ctx context.Context, arg UpdateDetalleReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDetalleReserva,
		arg.Idhabitacion,
		arg.Idtarifa,
		arg.Cantidadpersonas,
		arg.Precioaplicado,
		arg.Fechaentrada,
		arg.Fechasalida,
		arg.Iva,
		arg.Subtotal,
		arg.Total,
		arg.Iddetallereserva,
	)
}
