// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habitacion.sql

package dto

import (
	"context"
	"database/sql"

	decimal "github.com/shopspring/decimal"
)

const createHabitacion = `-- name: CreateHabitacion :execresult
INSERT INTO Habitacion (idTipoHab, numeroHabitacion)
VALUES (?, ?)
`

type CreateHabitacionParams struct {
	Idtipohab        int32  `json:"idtipohab"`
	Numerohabitacion string `json:"numerohabitacion"`
}

func (q *Queries) CreateHabitacion(ctx context.Context, arg CreateHabitacionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHabitacion, arg.Idtipohab, arg.Numerohabitacion)
}

const deleteHabitacion = `-- name: DeleteHabitacion :execresult
UPDATE Habitacion
SET estado = 0
WHERE idHabitacion = ?
`

func (q *Queries) DeleteHabitacion(ctx context.Context, idhabitacion int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteHabitacion, idhabitacion)
}

const getHabitacionById = `-- name: GetHabitacionById :one
SELECT idHabitacion, idTipoHab, numeroHabitacion, estado
FROM Habitacion
WHERE idHabitacion = ?
`

func (q *Queries) GetHabitacionById(ctx context.Context, idhabitacion int32) (Habitacion, error) {
	row := q.db.QueryRowContext(ctx, getHabitacionById, idhabitacion)
	var i Habitacion
	err := row.Scan(
		&i.Idhabitacion,
		&i.Idtipohab,
		&i.Numerohabitacion,
		&i.Estado,
	)
	return i, err
}

const getHabitacionByNumero = `-- name: GetHabitacionByNumero :one
SELECT idHabitacion, idTipoHab, numeroHabitacion, estado
FROM Habitacion
WHERE numeroHabitacion = ?
LIMIT 1
`

func (q *Queries) GetHabitacionByNumero(ctx context.Context, numerohabitacion string) (Habitacion, error) {
	row := q.db.QueryRowContext(ctx, getHabitacionByNumero, numerohabitacion)
	var i Habitacion
	err := row.Scan(
		&i.Idhabitacion,
		&i.Idtipohab,
		&i.Numerohabitacion,
		&i.Estado,
	)
	return i, err
}

const getHabitaciones = `-- name: GetHabitaciones :many
SELECT
    h.idHabitacion,
    h.idTipoHab,
    th.nombreTipoHab,
    h.numeroHabitacion,
    h.estado
FROM Habitacion h
INNER JOIN TipoHabitacion th
    ON h.idTipoHab = th.idTipoHabitacion
`

type GetHabitacionesRow struct {
	Idhabitacion     int32  `json:"idhabitacion"`
	Idtipohab        int32  `json:"idtipohab"`
	Nombretipohab    string `json:"nombretipohab"`
	Numerohabitacion string `json:"numerohabitacion"`
	Estado           int8   `json:"estado"`
}

func (q *Queries) GetHabitaciones(ctx context.Context) ([]GetHabitacionesRow, error) {
	rows, err := q.db.QueryContext(ctx, getHabitaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitacionesRow
	for rows.Next() {
		var i GetHabitacionesRow
		if err := rows.Scan(
			&i.Idhabitacion,
			&i.Idtipohab,
			&i.Nombretipohab,
			&i.Numerohabitacion,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitacionesByTipo = `-- name: GetHabitacionesByTipo :many
SELECT idHabitacion, idTipoHab, numeroHabitacion, estado
FROM Habitacion
WHERE idTipoHab = ?
`

func (q *Queries) GetHabitacionesByTipo(ctx context.Context, idtipohab int32) ([]Habitacion, error) {
	rows, err := q.db.QueryContext(ctx, getHabitacionesByTipo, idtipohab)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habitacion
	for rows.Next() {
		var i Habitacion
		if err := rows.Scan(
			&i.Idhabitacion,
			&i.Idtipohab,
			&i.Numerohabitacion,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitacionesDisponibles = `-- name: GetHabitacionesDisponibles :many
SELECT
    h.idHabitacion,
    h.numeroHabitacion,
    th.nombreTipoHab,
    t.idTarifa,
    t.nombreTarifa,
    t.precioBase,
    th.capacidadMaxima
FROM habitacion h
INNER JOIN tipohabitacion th
    ON h.idTipoHab = th.idTipoHabitacion
INNER JOIN tarifa t
    ON th.idTipoHabitacion = t.idTipoHabitacion
WHERE h.estado = 1
  AND th.estado = 1
  AND t.estado = 1
  AND t.desactivadaManual = 0
  AND CURDATE() BETWEEN t.fechaInicio AND t.fechaFin
`

type GetHabitacionesDisponiblesRow struct {
	Idhabitacion     int32           `json:"idhabitacion"`
	Numerohabitacion string          `json:"numerohabitacion"`
	Nombretipohab    string          `json:"nombretipohab"`
	Idtarifa         int32           `json:"idtarifa"`
	Nombretarifa     string          `json:"nombretarifa"`
	Preciobase       decimal.Decimal `json:"preciobase"`
	Capacidadmaxima  int32           `json:"capacidadmaxima"`
}

func (q *Queries) GetHabitacionesDisponibles(ctx context.Context) ([]GetHabitacionesDisponiblesRow, error) {
	rows, err := q.db.QueryContext(ctx, getHabitacionesDisponibles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitacionesDisponiblesRow
	for rows.Next() {
		var i GetHabitacionesDisponiblesRow
		if err := rows.Scan(
			&i.Idhabitacion,
			&i.Numerohabitacion,
			&i.Nombretipohab,
			&i.Idtarifa,
			&i.Nombretarifa,
			&i.Preciobase,
			&i.Capacidadmaxima,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabitacion = `-- name: UpdateHabitacion :execresult
UPDATE Habitacion
SET idTipoHab = ?, numeroHabitacion = ?, estado = ?
WHERE idHabitacion = ?
`

type UpdateHabitacionParams struct {
	Idtipohab        int32  `json:"idtipohab"`
	Numerohabitacion string `json:"numerohabitacion"`
	Estado           int8   `json:"estado"`
	Idhabitacion     int32  `json:"idhabitacion"`
}

func (q *Queries) UpdateHabitacion(ctx context.Context, arg UpdateHabitacionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateHabitacion,
		arg.Idtipohab,
		arg.Numerohabitacion,
		arg.Estado,
		arg.Idhabitacion,
	)
}

const updateEstadoHabitacion = `-- name: updateEstadoHabitacion :execresult
UPDATE Habitacion
SET estado = ?
WHERE idHabitacion = ?
`

type updateEstadoHabitacionParams struct {
	Estado       int8  `json:"estado"`
	Idhabitacion int32 `json:"idhabitacion"`
}

func (q *Queries) updateEstadoHabitacion(ctx context.Context, arg updateEstadoHabitacionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEstadoHabitacion, arg.Estado, arg.Idhabitacion)
}
