// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dto

import (
	"database/sql"
	"time"
)

type Cliente struct {
	Cedula        string `json:"cedula"`
	Idtipocliente int32  `json:"idtipocliente"`
	Nombre        string `json:"nombre"`
	Apellidos     string `json:"apellidos"`
	Telefono      string `json:"telefono"`
	Direccion     string `json:"direccion"`
	Estado        int8   `json:"estado"`
}

type Detallereserva struct {
	Iddetallereserva int32     `json:"iddetallereserva"`
	Idhabitacion     int32     `json:"idhabitacion"`
	Idreserva        int32     `json:"idreserva"`
	Idtarifa         int32     `json:"idtarifa"`
	Cantidadpersonas int32     `json:"cantidadpersonas"`
	Precioaplicado   string    `json:"precioaplicado"`
	Fechaentrada     time.Time `json:"fechaentrada"`
	Fechasalida      time.Time `json:"fechasalida"`
	Iva              string    `json:"iva"`
	Subtotal         string    `json:"subtotal"`
	Total            string    `json:"total"`
	Estado           int8      `json:"estado"`
}

type Habitacion struct {
	Idhabitacion     int32  `json:"idhabitacion"`
	Idtipohab        int32  `json:"idtipohab"`
	Numerohabitacion string `json:"numerohabitacion"`
	Estado           int8   `json:"estado"`
}

type Recepcionistum struct {
	Cedula    string `json:"cedula"`
	Nombre    string `json:"nombre"`
	Apellidos string `json:"apellidos"`
	Telefono  string `json:"telefono"`
	Correo    string `json:"correo"`
	Estado    int8   `json:"estado"`
}

type Reserva struct {
	Idreserva       int32     `json:"idreserva"`
	Idrecepcionista string    `json:"idrecepcionista"`
	Idcliente       string    `json:"idcliente"`
	Fechareserva    time.Time `json:"fechareserva"`
	Estadoreserva   string    `json:"estadoreserva"`
	Estado          int8      `json:"estado"`
	Iva             string    `json:"iva"`
	Subtotal        string    `json:"subtotal"`
	Total           string    `json:"total"`
}

type Tarifa struct {
	Idtarifa         int32          `json:"idtarifa"`
	Idtipohabitacion int32          `json:"idtipohabitacion"`
	Preciobase       string         `json:"preciobase"`
	Nombretarifa     string         `json:"nombretarifa"`
	Fechainicio      sql.NullTime   `json:"fechainicio"`
	Fechafin         sql.NullTime   `json:"fechafin"`
	Descripcion      sql.NullString `json:"descripcion"`
	Estado           int8           `json:"estado"`
}

type Tipocliente struct {
	Idtipocliente int32  `json:"idtipocliente"`
	Nombretipoc   string `json:"nombretipoc"`
	Descripcion   string `json:"descripcion"`
	Descuentobase string `json:"descuentobase"`
	Estado        int8   `json:"estado"`
}

type Tipohabitacion struct {
	Idtipohabitacion int32  `json:"idtipohabitacion"`
	Nombretipohab    string `json:"nombretipohab"`
	Descripcion      string `json:"descripcion"`
	Capacidadmaxima  int32  `json:"capacidadmaxima"`
	Estado           int8   `json:"estado"`
}

type User struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Role      sql.NullString `json:"role"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Estado    int8           `json:"estado"`
	Image     sql.NullString `json:"image"`
	Cedula    sql.NullString `json:"cedula"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}
