// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recepcionista.sql

package dto

import (
	"context"
	"database/sql"
)

const createRecepcionista = `-- name: CreateRecepcionista :execresult
INSERT INTO Recepcionista (
    cedula,
    nombre,
    apellidos,
    telefono,
    correo
)
VALUES (?, ?, ?, ?, ?)
`

type CreateRecepcionistaParams struct {
	Cedula    string `json:"cedula"`
	Nombre    string `json:"nombre"`
	Apellidos string `json:"apellidos"`
	Telefono  string `json:"telefono"`
	Correo    string `json:"correo"`
}

func (q *Queries) CreateRecepcionista(ctx context.Context, arg CreateRecepcionistaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRecepcionista,
		arg.Cedula,
		arg.Nombre,
		arg.Apellidos,
		arg.Telefono,
		arg.Correo,
	)
}

const deleteRecepcionista = `-- name: DeleteRecepcionista :execresult
UPDATE Recepcionista
SET estado = 0
WHERE cedula = ?
`

func (q *Queries) DeleteRecepcionista(ctx context.Context, cedula string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRecepcionista, cedula)
}

const getRecepcionistaByCedula = `-- name: GetRecepcionistaByCedula :one
SELECT
    cedula,
    nombre,
    apellidos,
    telefono,
    correo,
    estado
FROM Recepcionista
WHERE cedula = ?
`

func (q *Queries) GetRecepcionistaByCedula(ctx context.Context, cedula string) (Recepcionistum, error) {
	row := q.db.QueryRowContext(ctx, getRecepcionistaByCedula, cedula)
	var i Recepcionistum
	err := row.Scan(
		&i.Cedula,
		&i.Nombre,
		&i.Apellidos,
		&i.Telefono,
		&i.Correo,
		&i.Estado,
	)
	return i, err
}

const getRecepcionistas = `-- name: GetRecepcionistas :many
SELECT
    cedula,
    nombre,
    apellidos,
    telefono,
    correo,
    estado
FROM Recepcionista
`

func (q *Queries) GetRecepcionistas(ctx context.Context) ([]Recepcionistum, error) {
	rows, err := q.db.QueryContext(ctx, getRecepcionistas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recepcionistum
	for rows.Next() {
		var i Recepcionistum
		if err := rows.Scan(
			&i.Cedula,
			&i.Nombre,
			&i.Apellidos,
			&i.Telefono,
			&i.Correo,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecepcionistas = `-- name: SearchRecepcionistas :many
SELECT
    cedula,
    nombre,
    apellidos,
    telefono,
    correo,
    estado
FROM Recepcionista
WHERE
    CAST(cedula AS CHAR) LIKE CONCAT(?, '%')
    OR nombre LIKE CONCAT(?, '%')
    OR apellidos LIKE CONCAT(?, '%')
    OR telefono LIKE CONCAT(?, '%')
    OR correo LIKE CONCAT(?, '%')
`

type SearchRecepcionistasParams struct {
	CONCAT   interface{} `json:"CONCAT"`
	CONCAT_2 interface{} `json:"CONCAT_2"`
	CONCAT_3 interface{} `json:"CONCAT_3"`
	CONCAT_4 interface{} `json:"CONCAT_4"`
	CONCAT_5 interface{} `json:"CONCAT_5"`
}

func (q *Queries) SearchRecepcionistas(ctx context.Context, arg SearchRecepcionistasParams) ([]Recepcionistum, error) {
	rows, err := q.db.QueryContext(ctx, searchRecepcionistas,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.CONCAT_3,
		arg.CONCAT_4,
		arg.CONCAT_5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recepcionistum
	for rows.Next() {
		var i Recepcionistum
		if err := rows.Scan(
			&i.Cedula,
			&i.Nombre,
			&i.Apellidos,
			&i.Telefono,
			&i.Correo,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRecepcionistaEstado = `-- name: ToggleRecepcionistaEstado :execresult
UPDATE Recepcionista
SET estado = NOT estado
WHERE cedula = ?
`

func (q *Queries) ToggleRecepcionistaEstado(ctx context.Context, cedula string) (sql.Result, error) {
	return q.db.ExecContext(ctx, toggleRecepcionistaEstado, cedula)
}

const updateRecepcionista = `-- name: UpdateRecepcionista :execresult
UPDATE Recepcionista
SET
    nombre = ?,
    apellidos = ?,
    telefono = ?,
    correo = ?,
    estado = ?
WHERE cedula = ?
`

type UpdateRecepcionistaParams struct {
	Nombre    string `json:"nombre"`
	Apellidos string `json:"apellidos"`
	Telefono  string `json:"telefono"`
	Correo    string `json:"correo"`
	Estado    int8   `json:"estado"`
	Cedula    string `json:"cedula"`
}

func (q *Queries) UpdateRecepcionista(ctx context.Context, arg UpdateRecepcionistaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRecepcionista,
		arg.Nombre,
		arg.Apellidos,
		arg.Telefono,
		arg.Correo,
		arg.Estado,
		arg.Cedula,
	)
}
