// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reserva.sql

package dto

import (
	"context"
	"database/sql"
	"time"

	decimal "github.com/shopspring/decimal"
)

const createReserva = `-- name: CreateReserva :execresult
INSERT INTO Reserva (
    idRecepcionista,
    idCliente,
    fechaReserva,
    estadoReserva,
    iva,
    subTotal,
    total
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateReservaParams struct {
	Idrecepcionista string          `json:"idrecepcionista"`
	Idcliente       string          `json:"idcliente"`
	Fechareserva    time.Time       `json:"fechareserva"`
	Estadoreserva   string          `json:"estadoreserva"`
	Iva             decimal.Decimal `json:"iva"`
	Subtotal        decimal.Decimal `json:"subtotal"`
	Total           decimal.Decimal `json:"total"`
}

func (q *Queries) CreateReserva(ctx context.Context, arg CreateReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReserva,
		arg.Idrecepcionista,
		arg.Idcliente,
		arg.Fechareserva,
		arg.Estadoreserva,
		arg.Iva,
		arg.Subtotal,
		arg.Total,
	)
}

const getReservaById = `-- name: GetReservaById :one
SELECT
    r.idReserva,
    r.idRecepcionista,
    r.idCliente,
    CONCAT(c.nombre, ' ', c.apellidos) AS nombreCliente,
    CONCAT(re.nombre, ' ', re.apellidos) AS nombreRecepcionista,
    r.fechaReserva,
    r.estadoReserva,
    r.estado,
    r.iva,
    r.subTotal,
    r.total
FROM Reserva r
INNER JOIN cliente c ON r.idCliente = c.cedula
INNER JOIN recepcionista re ON r.idRecepcionista = re.cedula
WHERE r.idReserva = ? AND r.estado = 1
`

type GetReservaByIdRow struct {
	Idreserva           int32           `json:"idreserva"`
	Idrecepcionista     string          `json:"idrecepcionista"`
	Idcliente           string          `json:"idcliente"`
	Nombrecliente       string          `json:"nombrecliente"`
	Nombrerecepcionista string          `json:"nombrerecepcionista"`
	Fechareserva        time.Time       `json:"fechareserva"`
	Estadoreserva       string          `json:"estadoreserva"`
	Estado              int8            `json:"estado"`
	Iva                 decimal.Decimal `json:"iva"`
	Subtotal            decimal.Decimal `json:"subtotal"`
	Total               decimal.Decimal `json:"total"`
}

func (q *Queries) GetReservaById(ctx context.Context, idreserva int32) (GetReservaByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getReservaById, idreserva)
	var i GetReservaByIdRow
	err := row.Scan(
		&i.Idreserva,
		&i.Idrecepcionista,
		&i.Idcliente,
		&i.Nombrecliente,
		&i.Nombrerecepcionista,
		&i.Fechareserva,
		&i.Estadoreserva,
		&i.Estado,
		&i.Iva,
		&i.Subtotal,
		&i.Total,
	)
	return i, err
}

const getReservas = `-- name: GetReservas :many
SELECT
    r.idReserva,
    r.idRecepcionista,
    r.idCliente,
    CONCAT(c.nombre, ' ', c.apellidos) AS nombreCliente,
    CONCAT(re.nombre, ' ', re.apellidos) AS nombreRecepcionista,
    r.fechaReserva,
    r.estadoReserva,
    r.estado,
    r.iva,
    r.subTotal,
    r.total
FROM Reserva r
INNER JOIN cliente c ON r.idCliente = c.cedula
INNER JOIN recepcionista re ON r.idRecepcionista = re.cedula
WHERE r.estado = 1
`

type GetReservasRow struct {
	Idreserva           int32           `json:"idreserva"`
	Idrecepcionista     string          `json:"idrecepcionista"`
	Idcliente           string          `json:"idcliente"`
	Nombrecliente       string          `json:"nombrecliente"`
	Nombrerecepcionista string          `json:"nombrerecepcionista"`
	Fechareserva        time.Time       `json:"fechareserva"`
	Estadoreserva       string          `json:"estadoreserva"`
	Estado              int8            `json:"estado"`
	Iva                 decimal.Decimal `json:"iva"`
	Subtotal            decimal.Decimal `json:"subtotal"`
	Total               decimal.Decimal `json:"total"`
}

func (q *Queries) GetReservas(ctx context.Context) ([]GetReservasRow, error) {
	rows, err := q.db.QueryContext(ctx, getReservas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservasRow
	for rows.Next() {
		var i GetReservasRow
		if err := rows.Scan(
			&i.Idreserva,
			&i.Idrecepcionista,
			&i.Idcliente,
			&i.Nombrecliente,
			&i.Nombrerecepcionista,
			&i.Fechareserva,
			&i.Estadoreserva,
			&i.Estado,
			&i.Iva,
			&i.Subtotal,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservasByCliente = `-- name: GetReservasByCliente :many
SELECT
    r.idReserva,
    r.idRecepcionista,
    r.idCliente,
    CONCAT(c.nombre, ' ', c.apellidos) AS nombreCliente,
    CONCAT(re.nombre, ' ', re.apellidos) AS nombreRecepcionista,
    r.fechaReserva,
    r.estadoReserva,
    r.estado,
    r.iva,
    r.subTotal,
    r.total
FROM Reserva r
INNER JOIN cliente c ON r.idCliente = c.cedula
INNER JOIN recepcionista re ON r.idRecepcionista = re.cedula
WHERE r.idCliente = ? AND r.estado = 1
`

type GetReservasByClienteRow struct {
	Idreserva           int32           `json:"idreserva"`
	Idrecepcionista     string          `json:"idrecepcionista"`
	Idcliente           string          `json:"idcliente"`
	Nombrecliente       string          `json:"nombrecliente"`
	Nombrerecepcionista string          `json:"nombrerecepcionista"`
	Fechareserva        time.Time       `json:"fechareserva"`
	Estadoreserva       string          `json:"estadoreserva"`
	Estado              int8            `json:"estado"`
	Iva                 decimal.Decimal `json:"iva"`
	Subtotal            decimal.Decimal `json:"subtotal"`
	Total               decimal.Decimal `json:"total"`
}

func (q *Queries) GetReservasByCliente(ctx context.Context, idcliente string) ([]GetReservasByClienteRow, error) {
	rows, err := q.db.QueryContext(ctx, getReservasByCliente, idcliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservasByClienteRow
	for rows.Next() {
		var i GetReservasByClienteRow
		if err := rows.Scan(
			&i.Idreserva,
			&i.Idrecepcionista,
			&i.Idcliente,
			&i.Nombrecliente,
			&i.Nombrerecepcionista,
			&i.Fechareserva,
			&i.Estadoreserva,
			&i.Estado,
			&i.Iva,
			&i.Subtotal,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservasByRecepcionista = `-- name: GetReservasByRecepcionista :many
SELECT
    r.idReserva,
    r.idRecepcionista,
    r.idCliente,
    CONCAT(c.nombre, ' ', c.apellidos) AS nombreCliente,
    CONCAT(re.nombre, ' ', re.apellidos) AS nombreRecepcionista,
    r.fechaReserva,
    r.estadoReserva,
    r.estado,
    r.iva,
    r.subTotal,
    r.total
FROM Reserva r
INNER JOIN cliente c ON r.idCliente = c.cedula
INNER JOIN recepcionista re ON r.idRecepcionista = re.cedula
WHERE r.idRecepcionista = ? AND r.estado = 1
`

type GetReservasByRecepcionistaRow struct {
	Idreserva           int32           `json:"idreserva"`
	Idrecepcionista     string          `json:"idrecepcionista"`
	Idcliente           string          `json:"idcliente"`
	Nombrecliente       string          `json:"nombrecliente"`
	Nombrerecepcionista string          `json:"nombrerecepcionista"`
	Fechareserva        time.Time       `json:"fechareserva"`
	Estadoreserva       string          `json:"estadoreserva"`
	Estado              int8            `json:"estado"`
	Iva                 decimal.Decimal `json:"iva"`
	Subtotal            decimal.Decimal `json:"subtotal"`
	Total               decimal.Decimal `json:"total"`
}

func (q *Queries) GetReservasByRecepcionista(ctx context.Context, idrecepcionista string) ([]GetReservasByRecepcionistaRow, error) {
	rows, err := q.db.QueryContext(ctx, getReservasByRecepcionista, idrecepcionista)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReservasByRecepcionistaRow
	for rows.Next() {
		var i GetReservasByRecepcionistaRow
		if err := rows.Scan(
			&i.Idreserva,
			&i.Idrecepcionista,
			&i.Idcliente,
			&i.Nombrecliente,
			&i.Nombrerecepcionista,
			&i.Fechareserva,
			&i.Estadoreserva,
			&i.Estado,
			&i.Iva,
			&i.Subtotal,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleReserva = `-- name: ToggleReserva :execresult
UPDATE reserva
SET estado = NOT estado
WHERE idReserva = ?
`

func (q *Queries) ToggleReserva(ctx context.Context, idreserva int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, toggleReserva, idreserva)
}

const updateEstadoReserva = `-- name: UpdateEstadoReserva :execresult
UPDATE Reserva
SET estadoReserva = ?
WHERE idReserva = ?
`

type UpdateEstadoReservaParams struct {
	Estadoreserva string `json:"estadoreserva"`
	Idreserva     int32  `json:"idreserva"`
}

func (q *Queries) UpdateEstadoReserva(ctx context.Context, arg UpdateEstadoReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEstadoReserva, arg.Estadoreserva, arg.Idreserva)
}

const updateReserva = `-- name: UpdateReserva :execresult
UPDATE Reserva
SET
    idRecepcionista = ?,
    idCliente = ?,
    fechaReserva = ?,
    estadoReserva = ?,
    estado = ?,
    iva = ?,
    subTotal = ?,
    total = ?
WHERE idReserva = ?
`

type UpdateReservaParams struct {
	Idrecepcionista string          `json:"idrecepcionista"`
	Idcliente       string          `json:"idcliente"`
	Fechareserva    time.Time       `json:"fechareserva"`
	Estadoreserva   string          `json:"estadoreserva"`
	Estado          int8            `json:"estado"`
	Iva             decimal.Decimal `json:"iva"`
	Subtotal        decimal.Decimal `json:"subtotal"`
	Total           decimal.Decimal `json:"total"`
	Idreserva       int32           `json:"idreserva"`
}

func (q *Queries) UpdateReserva(ctx context.Context, arg UpdateReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateReserva,
		arg.Idrecepcionista,
		arg.Idcliente,
		arg.Fechareserva,
		arg.Estadoreserva,
		arg.Estado,
		arg.Iva,
		arg.Subtotal,
		arg.Total,
		arg.Idreserva,
	)
}
