// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reserva.sql

package dto

import (
	"context"
	"database/sql"
	"time"
)

const createReserva = `-- name: CreateReserva :execresult
INSERT INTO Reserva (
    idRecepcionista,
    idCliente,
    fechaReserva,
    estadoReserva,
    iva,
    subTotal,
    total
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateReservaParams struct {
	Idrecepcionista string    `json:"idrecepcionista"`
	Idcliente       string    `json:"idcliente"`
	Fechareserva    time.Time `json:"fechareserva"`
	Estadoreserva   string    `json:"estadoreserva"`
	Iva             string    `json:"iva"`
	Subtotal        string    `json:"subtotal"`
	Total           string    `json:"total"`
}

func (q *Queries) CreateReserva(ctx context.Context, arg CreateReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createReserva,
		arg.Idrecepcionista,
		arg.Idcliente,
		arg.Fechareserva,
		arg.Estadoreserva,
		arg.Iva,
		arg.Subtotal,
		arg.Total,
	)
}

const deleteReserva = `-- name: DeleteReserva :execresult
UPDATE reserva
SET estado = CASE
    WHEN estado = 1 THEN 0
    ELSE 1
END
WHERE idReserva = ?
`

func (q *Queries) DeleteReserva(ctx context.Context, idreserva int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteReserva, idreserva)
}

const getReservaById = `-- name: GetReservaById :one
SELECT
    idReserva,
    idRecepcionista,
    idCliente,
    fechaReserva,
    estadoReserva,
    estado,
    iva,
    subTotal,
    total
FROM Reserva
WHERE idReserva = ? AND estado = 1
`

func (q *Queries) GetReservaById(ctx context.Context, idreserva int32) (Reserva, error) {
	row := q.db.QueryRowContext(ctx, getReservaById, idreserva)
	var i Reserva
	err := row.Scan(
		&i.Idreserva,
		&i.Idrecepcionista,
		&i.Idcliente,
		&i.Fechareserva,
		&i.Estadoreserva,
		&i.Estado,
		&i.Iva,
		&i.Subtotal,
		&i.Total,
	)
	return i, err
}

const getReservas = `-- name: GetReservas :many
SELECT
    idReserva,
    idRecepcionista,
    idCliente,
    fechaReserva,
    estadoReserva,
    estado,
    iva,
    subTotal,
    total
FROM Reserva
WHERE estado = 1
`

func (q *Queries) GetReservas(ctx context.Context) ([]Reserva, error) {
	rows, err := q.db.QueryContext(ctx, getReservas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reserva
	for rows.Next() {
		var i Reserva
		if err := rows.Scan(
			&i.Idreserva,
			&i.Idrecepcionista,
			&i.Idcliente,
			&i.Fechareserva,
			&i.Estadoreserva,
			&i.Estado,
			&i.Iva,
			&i.Subtotal,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservasByCliente = `-- name: GetReservasByCliente :many
SELECT
    idReserva,
    idRecepcionista,
    idCliente,
    fechaReserva,
    estadoReserva,
    estado,
    iva,
    subTotal,
    total
FROM Reserva
WHERE idCliente = ? AND estado = 1
`

func (q *Queries) GetReservasByCliente(ctx context.Context, idcliente string) ([]Reserva, error) {
	rows, err := q.db.QueryContext(ctx, getReservasByCliente, idcliente)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reserva
	for rows.Next() {
		var i Reserva
		if err := rows.Scan(
			&i.Idreserva,
			&i.Idrecepcionista,
			&i.Idcliente,
			&i.Fechareserva,
			&i.Estadoreserva,
			&i.Estado,
			&i.Iva,
			&i.Subtotal,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservasByRecepcionista = `-- name: GetReservasByRecepcionista :many
SELECT
    idReserva,
    idRecepcionista,
    idCliente,
    fechaReserva,
    estadoReserva,
    estado,
    iva,
    subTotal,
    total
FROM Reserva
WHERE idRecepcionista = ? AND estado = 1
`

func (q *Queries) GetReservasByRecepcionista(ctx context.Context, idrecepcionista string) ([]Reserva, error) {
	rows, err := q.db.QueryContext(ctx, getReservasByRecepcionista, idrecepcionista)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reserva
	for rows.Next() {
		var i Reserva
		if err := rows.Scan(
			&i.Idreserva,
			&i.Idrecepcionista,
			&i.Idcliente,
			&i.Fechareserva,
			&i.Estadoreserva,
			&i.Estado,
			&i.Iva,
			&i.Subtotal,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEstadoReserva = `-- name: UpdateEstadoReserva :execresult
UPDATE Reserva
SET estadoReserva = ?
WHERE idReserva = ?
`

type UpdateEstadoReservaParams struct {
	Estadoreserva string `json:"estadoreserva"`
	Idreserva     int32  `json:"idreserva"`
}

func (q *Queries) UpdateEstadoReserva(ctx context.Context, arg UpdateEstadoReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEstadoReserva, arg.Estadoreserva, arg.Idreserva)
}

const updateReserva = `-- name: UpdateReserva :execresult
UPDATE Reserva
SET
    idRecepcionista = ?,
    idCliente = ?,
    fechaReserva = ?,
    estadoReserva = ?,
    estado = ?,
    iva = ?,
    subTotal = ?,
    total = ?
WHERE idReserva = ?
`

type UpdateReservaParams struct {
	Idrecepcionista string    `json:"idrecepcionista"`
	Idcliente       string    `json:"idcliente"`
	Fechareserva    time.Time `json:"fechareserva"`
	Estadoreserva   string    `json:"estadoreserva"`
	Estado          int8      `json:"estado"`
	Iva             string    `json:"iva"`
	Subtotal        string    `json:"subtotal"`
	Total           string    `json:"total"`
	Idreserva       int32     `json:"idreserva"`
}

func (q *Queries) UpdateReserva(ctx context.Context, arg UpdateReservaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateReserva,
		arg.Idrecepcionista,
		arg.Idcliente,
		arg.Fechareserva,
		arg.Estadoreserva,
		arg.Estado,
		arg.Iva,
		arg.Subtotal,
		arg.Total,
		arg.Idreserva,
	)
}
