// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tarifa.sql

package dto

import (
	"context"
	"database/sql"
	"time"

	decimal "github.com/shopspring/decimal"
)

const activarTarifaSiEstaVigentePorUsuario = `-- name: ActivarTarifaSiEstaVigentePorUsuario :execresult
UPDATE tarifa
SET estado = 1,
desactivadaManual = 0
WHERE idTarifa = ?
AND fechaInicio <= CURDATE()
AND fechaFin >= CURDATE()
`

func (q *Queries) ActivarTarifaSiEstaVigentePorUsuario(ctx context.Context, idtarifa int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, activarTarifaSiEstaVigentePorUsuario, idtarifa)
}

const activarTarifasVigentesAutomatico = `-- name: ActivarTarifasVigentesAutomatico :exec
UPDATE tarifa
SET estado = 1
WHERE estado = 0
AND desactivadaManual = 0
AND fechaInicio <= CURDATE()
AND fechaFin >= CURDATE()
`

func (q *Queries) ActivarTarifasVigentesAutomatico(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, activarTarifasVigentesAutomatico)
	return err
}

const createTarifa = `-- name: CreateTarifa :execresult
INSERT INTO tarifa (idTipoHabitacion, precioBase, nombreTarifa,fechaInicio,fechaFin,descripcion,estado)
VALUES (?, ?, ?, ?, ? , ?, ?)
`

type CreateTarifaParams struct {
	Idtipohabitacion int32           `json:"idtipohabitacion"`
	Preciobase       decimal.Decimal `json:"preciobase"`
	Nombretarifa     string          `json:"nombretarifa"`
	Fechainicio      sql.NullTime    `json:"fechainicio"`
	Fechafin         sql.NullTime    `json:"fechafin"`
	Descripcion      sql.NullString  `json:"descripcion"`
	Estado           int8            `json:"estado"`
}

func (q *Queries) CreateTarifa(ctx context.Context, arg CreateTarifaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTarifa,
		arg.Idtipohabitacion,
		arg.Preciobase,
		arg.Nombretarifa,
		arg.Fechainicio,
		arg.Fechafin,
		arg.Descripcion,
		arg.Estado,
	)
}

const desactivarTarifaPorUsuario = `-- name: DesactivarTarifaPorUsuario :execresult
UPDATE tarifa
SET estado = 0,
desactivadaManual = 1
WHERE idTarifa = ?
`

func (q *Queries) DesactivarTarifaPorUsuario(ctx context.Context, idtarifa int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, desactivarTarifaPorUsuario, idtarifa)
}

const getEstadisticasTarifa = `-- name: GetEstadisticasTarifa :one
SELECT
  COUNT(dr.idDetalleReserva) AS totalReservas,
  CAST(MAX(r.fechaReserva) AS DATETIME) AS ultimaVezUtilizada
FROM detallereserva dr
INNER JOIN reserva r
ON dr.idReserva = r.idReserva
WHERE dr.idTarifa = ?
`

type GetEstadisticasTarifaRow struct {
	Totalreservas      int64     `json:"totalreservas"`
	Ultimavezutilizada time.Time `json:"ultimavezutilizada"`
}

func (q *Queries) GetEstadisticasTarifa(ctx context.Context, idtarifa int32) (GetEstadisticasTarifaRow, error) {
	row := q.db.QueryRowContext(ctx, getEstadisticasTarifa, idtarifa)
	var i GetEstadisticasTarifaRow
	err := row.Scan(&i.Totalreservas, &i.Ultimavezutilizada)
	return i, err
}

const getTarifaByNombre = `-- name: GetTarifaByNombre :one
SELECT 
    t.idTarifa,
    t.nombreTarifa,
    th.nombreTipoHab AS tipoHabitacion,
    t.precioBase,
    t.fechaInicio,
    t.fechaFin,
    t.estado
FROM Tarifa t
INNER JOIN TipoHabitacion th 
    ON t.idTipoHabitacion = th.idTipoHabitacion
WHERE t.nombreTarifa = ?
`

type GetTarifaByNombreRow struct {
	Idtarifa       int32           `json:"idtarifa"`
	Nombretarifa   string          `json:"nombretarifa"`
	Tipohabitacion string          `json:"tipohabitacion"`
	Preciobase     decimal.Decimal `json:"preciobase"`
	Fechainicio    sql.NullTime    `json:"fechainicio"`
	Fechafin       sql.NullTime    `json:"fechafin"`
	Estado         int8            `json:"estado"`
}

func (q *Queries) GetTarifaByNombre(ctx context.Context, nombretarifa string) (GetTarifaByNombreRow, error) {
	row := q.db.QueryRowContext(ctx, getTarifaByNombre, nombretarifa)
	var i GetTarifaByNombreRow
	err := row.Scan(
		&i.Idtarifa,
		&i.Nombretarifa,
		&i.Tipohabitacion,
		&i.Preciobase,
		&i.Fechainicio,
		&i.Fechafin,
		&i.Estado,
	)
	return i, err
}

const getTarifas = `-- name: GetTarifas :many
SELECT 
    t.idTarifa,
    t.nombreTarifa,
    th.nombreTipoHab AS tipoHabitacion,
    t.precioBase,
    t.fechaInicio,
    t.fechaFin,
    t.descripcion,
    t.estado,
    t.desactivadaManual
FROM Tarifa t
INNER JOIN TipoHabitacion th 
    ON t.idTipoHabitacion = th.idTipoHabitacion
`

type GetTarifasRow struct {
	Idtarifa          int32           `json:"idtarifa"`
	Nombretarifa      string          `json:"nombretarifa"`
	Tipohabitacion    string          `json:"tipohabitacion"`
	Preciobase        decimal.Decimal `json:"preciobase"`
	Fechainicio       sql.NullTime    `json:"fechainicio"`
	Fechafin          sql.NullTime    `json:"fechafin"`
	Descripcion       sql.NullString  `json:"descripcion"`
	Estado            int8            `json:"estado"`
	Desactivadamanual int8            `json:"desactivadamanual"`
}

func (q *Queries) GetTarifas(ctx context.Context) ([]GetTarifasRow, error) {
	rows, err := q.db.QueryContext(ctx, getTarifas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTarifasRow
	for rows.Next() {
		var i GetTarifasRow
		if err := rows.Scan(
			&i.Idtarifa,
			&i.Nombretarifa,
			&i.Tipohabitacion,
			&i.Preciobase,
			&i.Fechainicio,
			&i.Fechafin,
			&i.Descripcion,
			&i.Estado,
			&i.Desactivadamanual,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTarifa = `-- name: UpdateTarifa :execresult
UPDATE tarifa
SET
    idTipoHabitacion = COALESCE(?, idTipoHabitacion),
    precioBase       = COALESCE(?, precioBase),
    nombreTarifa     = COALESCE(?, nombreTarifa),
    fechaInicio      = COALESCE(?, fechaInicio),
    fechaFin         = COALESCE(?, fechaFin),
    descripcion      = ?
WHERE idTarifa = ?
`

type UpdateTarifaParams struct {
	Idtipohabitacion sql.NullInt32  `json:"idtipohabitacion"`
	Preciobase       sql.NullString `json:"preciobase"`
	Nombretarifa     sql.NullString `json:"nombretarifa"`
	Fechainicio      sql.NullTime   `json:"fechainicio"`
	Fechafin         sql.NullTime   `json:"fechafin"`
	Descripcion      sql.NullString `json:"descripcion"`
	Idtarifa         int32          `json:"idtarifa"`
}

func (q *Queries) UpdateTarifa(ctx context.Context, arg UpdateTarifaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTarifa,
		arg.Idtipohabitacion,
		arg.Preciobase,
		arg.Nombretarifa,
		arg.Fechainicio,
		arg.Fechafin,
		arg.Descripcion,
		arg.Idtarifa,
	)
}

const updateTarifasVencidasAutomatico = `-- name: UpdateTarifasVencidasAutomatico :exec
UPDATE tarifa
SET estado = 0,
    desactivadaManual = 0
WHERE fechaFin < CURDATE()
`

func (q *Queries) UpdateTarifasVencidasAutomatico(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateTarifasVencidasAutomatico)
	return err
}
