// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tarifa.sql

package dto

import (
	"context"
	"database/sql"
)

const createTarifa = `-- name: CreateTarifa :execresult
INSERT INTO tarifa (idTipoHabitacion, precioBase, nombreTarifa,fechaInicio,fechaFin)
VALUES (?, ?, ?, ?,?)
`

type CreateTarifaParams struct {
	Idtipohabitacion int32        `json:"idtipohabitacion"`
	Preciobase       string       `json:"preciobase"`
	Nombretarifa     string       `json:"nombretarifa"`
	Fechainicio      sql.NullTime `json:"fechainicio"`
	Fechafin         sql.NullTime `json:"fechafin"`
}

func (q *Queries) CreateTarifa(ctx context.Context, arg CreateTarifaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTarifa,
		arg.Idtipohabitacion,
		arg.Preciobase,
		arg.Nombretarifa,
		arg.Fechainicio,
		arg.Fechafin,
	)
}

const deleteTarifa = `-- name: DeleteTarifa :execresult
UPDATE tarifa
SET estado = CASE
    WHEN estado = 1 THEN 0
    ELSE 1
END
WHERE idTarifa = ?
`

func (q *Queries) DeleteTarifa(ctx context.Context, idtarifa int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTarifa, idtarifa)
}

const getTarifaByNombre = `-- name: GetTarifaByNombre :one
SELECT 
    t.idTarifa,
    t.nombreTarifa,
    th.nombreTipoHab AS tipoHabitacion,
    t.precioBase,
    t.fechaInicio,
    t.fechaFin,
    t.estado
FROM Tarifa t
INNER JOIN TipoHabitacion th 
    ON t.idTipoHabitacion = th.idTipoHabitacion
WHERE t.nombreTarifa = ?
`

type GetTarifaByNombreRow struct {
	Idtarifa       int32        `json:"idtarifa"`
	Nombretarifa   string       `json:"nombretarifa"`
	Tipohabitacion string       `json:"tipohabitacion"`
	Preciobase     string       `json:"preciobase"`
	Fechainicio    sql.NullTime `json:"fechainicio"`
	Fechafin       sql.NullTime `json:"fechafin"`
	Estado         int8         `json:"estado"`
}

func (q *Queries) GetTarifaByNombre(ctx context.Context, nombretarifa string) (GetTarifaByNombreRow, error) {
	row := q.db.QueryRowContext(ctx, getTarifaByNombre, nombretarifa)
	var i GetTarifaByNombreRow
	err := row.Scan(
		&i.Idtarifa,
		&i.Nombretarifa,
		&i.Tipohabitacion,
		&i.Preciobase,
		&i.Fechainicio,
		&i.Fechafin,
		&i.Estado,
	)
	return i, err
}

const getTarifas = `-- name: GetTarifas :many
SELECT 
    t.idTarifa,
    t.nombreTarifa,
    th.nombreTipoHab AS tipoHabitacion,
    t.precioBase,
    t.fechaInicio,
    t.fechaFin,
    t.estado
FROM Tarifa t
INNER JOIN TipoHabitacion th 
    ON t.idTipoHabitacion = th.idTipoHabitacion
`

type GetTarifasRow struct {
	Idtarifa       int32        `json:"idtarifa"`
	Nombretarifa   string       `json:"nombretarifa"`
	Tipohabitacion string       `json:"tipohabitacion"`
	Preciobase     string       `json:"preciobase"`
	Fechainicio    sql.NullTime `json:"fechainicio"`
	Fechafin       sql.NullTime `json:"fechafin"`
	Estado         int8         `json:"estado"`
}

func (q *Queries) GetTarifas(ctx context.Context) ([]GetTarifasRow, error) {
	rows, err := q.db.QueryContext(ctx, getTarifas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTarifasRow
	for rows.Next() {
		var i GetTarifasRow
		if err := rows.Scan(
			&i.Idtarifa,
			&i.Nombretarifa,
			&i.Tipohabitacion,
			&i.Preciobase,
			&i.Fechainicio,
			&i.Fechafin,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTarifa = `-- name: UpdateTarifa :execresult
UPDATE tarifa
SET
    idTipoHabitacion = COALESCE(?, idTipoHabitacion),
    precioBase       = COALESCE(?, precioBase),
    nombreTarifa     = COALESCE(?, nombreTarifa),
    fechaInicio      = COALESCE(?, fechaInicio),
    fechaFin         = COALESCE(?, fechaFin)
WHERE idTarifa = ?
`

type UpdateTarifaParams struct {
	Idtipohabitacion sql.NullInt32  `json:"idtipohabitacion"`
	Preciobase       sql.NullString `json:"preciobase"`
	Nombretarifa     sql.NullString `json:"nombretarifa"`
	Fechainicio      sql.NullTime   `json:"fechainicio"`
	Fechafin         sql.NullTime   `json:"fechafin"`
	Idtarifa         int32          `json:"idtarifa"`
}

func (q *Queries) UpdateTarifa(ctx context.Context, arg UpdateTarifaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTarifa,
		arg.Idtipohabitacion,
		arg.Preciobase,
		arg.Nombretarifa,
		arg.Fechainicio,
		arg.Fechafin,
		arg.Idtarifa,
	)
}
