// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tipoHabitacion.sql

package dto

import (
	"context"
	"database/sql"
)

const createTipoHabitacion = `-- name: CreateTipoHabitacion :execresult
INSERT INTO TipoHabitacion (nombreTipoHab, descripcion, capacidadMaxima)
VALUES (?, ?, ?)
`

type CreateTipoHabitacionParams struct {
	Nombretipohab   string `json:"nombretipohab"`
	Descripcion     string `json:"descripcion"`
	Capacidadmaxima int32  `json:"capacidadmaxima"`
}

func (q *Queries) CreateTipoHabitacion(ctx context.Context, arg CreateTipoHabitacionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTipoHabitacion, arg.Nombretipohab, arg.Descripcion, arg.Capacidadmaxima)
}

const deleteTipoHabitacion = `-- name: DeleteTipoHabitacion :execresult
UPDATE TipoHabitacion
SET estado = 0
WHERE idTipoHabitacion = ?
`

func (q *Queries) DeleteTipoHabitacion(ctx context.Context, idtipohabitacion int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTipoHabitacion, idtipohabitacion)
}

const getTipoHabitacionById = `-- name: GetTipoHabitacionById :one
SELECT idTipoHabitacion, nombreTipoHab, descripcion, capacidadMaxima, estado
FROM TipoHabitacion
WHERE idTipoHabitacion = ? AND estado = 1
`

func (q *Queries) GetTipoHabitacionById(ctx context.Context, idtipohabitacion int32) (Tipohabitacion, error) {
	row := q.db.QueryRowContext(ctx, getTipoHabitacionById, idtipohabitacion)
	var i Tipohabitacion
	err := row.Scan(
		&i.Idtipohabitacion,
		&i.Nombretipohab,
		&i.Descripcion,
		&i.Capacidadmaxima,
		&i.Estado,
	)
	return i, err
}

const getTipoHabitaciones = `-- name: GetTipoHabitaciones :many
SELECT idTipoHabitacion, nombreTipoHab, descripcion, capacidadMaxima, estado
FROM TipoHabitacion
WHERE estado = 1
`

func (q *Queries) GetTipoHabitaciones(ctx context.Context) ([]Tipohabitacion, error) {
	rows, err := q.db.QueryContext(ctx, getTipoHabitaciones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tipohabitacion
	for rows.Next() {
		var i Tipohabitacion
		if err := rows.Scan(
			&i.Idtipohabitacion,
			&i.Nombretipohab,
			&i.Descripcion,
			&i.Capacidadmaxima,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTipoHabitacion = `-- name: UpdateTipoHabitacion :execresult
UPDATE TipoHabitacion
SET nombreTipoHab = ?, descripcion = ?, capacidadMaxima = ?, estado = ?
WHERE idTipoHabitacion = ?
`

type UpdateTipoHabitacionParams struct {
	Nombretipohab    string `json:"nombretipohab"`
	Descripcion      string `json:"descripcion"`
	Capacidadmaxima  int32  `json:"capacidadmaxima"`
	Estado           int8   `json:"estado"`
	Idtipohabitacion int32  `json:"idtipohabitacion"`
}

func (q *Queries) UpdateTipoHabitacion(ctx context.Context, arg UpdateTipoHabitacionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTipoHabitacion,
		arg.Nombretipohab,
		arg.Descripcion,
		arg.Capacidadmaxima,
		arg.Estado,
		arg.Idtipohabitacion,
	)
}

const updateEstadoTipoHabitacion = `-- name: updateEstadoTipoHabitacion :execresult
UPDATE TipoHabitacion
SET estado = ?
WHERE idTipoHabitacion = ?
`

type updateEstadoTipoHabitacionParams struct {
	Estado           int8  `json:"estado"`
	Idtipohabitacion int32 `json:"idtipohabitacion"`
}

func (q *Queries) updateEstadoTipoHabitacion(ctx context.Context, arg updateEstadoTipoHabitacionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateEstadoTipoHabitacion, arg.Estado, arg.Idtipohabitacion)
}
