// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tipoCliente.sql

package dto

import (
	"context"
	"database/sql"

	decimal "github.com/shopspring/decimal"
)

const createTipoCliente = `-- name: CreateTipoCliente :execresult
INSERT INTO tipoCliente (
    nombreTipoC,
    descripcion,
    descuentoBase
)
VALUES (?, ?, ?)
`

type CreateTipoClienteParams struct {
	Nombretipoc   string          `json:"nombretipoc"`
	Descripcion   string          `json:"descripcion"`
	Descuentobase decimal.Decimal `json:"descuentobase"`
}

func (q *Queries) CreateTipoCliente(ctx context.Context, arg CreateTipoClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTipoCliente, arg.Nombretipoc, arg.Descripcion, arg.Descuentobase)
}

const deleteTipoCliente = `-- name: DeleteTipoCliente :execresult
UPDATE tipoCliente
SET estado = 0
WHERE idTipoCliente = ?
`

func (q *Queries) DeleteTipoCliente(ctx context.Context, idtipocliente int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteTipoCliente, idtipocliente)
}

const getTipoClienteById = `-- name: GetTipoClienteById :one
SELECT
    idTipoCliente,
    nombreTipoC,
    descripcion,
    descuentoBase,
    estado
FROM tipoCliente
WHERE idTipoCliente = ?
`

func (q *Queries) GetTipoClienteById(ctx context.Context, idtipocliente int32) (Tipocliente, error) {
	row := q.db.QueryRowContext(ctx, getTipoClienteById, idtipocliente)
	var i Tipocliente
	err := row.Scan(
		&i.Idtipocliente,
		&i.Nombretipoc,
		&i.Descripcion,
		&i.Descuentobase,
		&i.Estado,
	)
	return i, err
}

const getTipoClientes = `-- name: GetTipoClientes :many
SELECT
    idTipoCliente,
    nombreTipoC,
    descripcion,
    descuentoBase,
    estado
FROM tipoCliente
`

func (q *Queries) GetTipoClientes(ctx context.Context) ([]Tipocliente, error) {
	rows, err := q.db.QueryContext(ctx, getTipoClientes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tipocliente
	for rows.Next() {
		var i Tipocliente
		if err := rows.Scan(
			&i.Idtipocliente,
			&i.Nombretipoc,
			&i.Descripcion,
			&i.Descuentobase,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTipoClientes = `-- name: SearchTipoClientes :many
SELECT
    idTipoCliente,
    nombreTipoC,
    descripcion,
    descuentoBase,
    estado
FROM tipoCliente
WHERE
    CAST(idTipoCliente AS CHAR) LIKE CONCAT(?, '%')
    OR nombreTipoC LIKE CONCAT(?, '%')
    OR descripcion LIKE CONCAT(?, '%')
`

type SearchTipoClientesParams struct {
	CONCAT   interface{} `json:"CONCAT"`
	CONCAT_2 interface{} `json:"CONCAT_2"`
	CONCAT_3 interface{} `json:"CONCAT_3"`
}

func (q *Queries) SearchTipoClientes(ctx context.Context, arg SearchTipoClientesParams) ([]Tipocliente, error) {
	rows, err := q.db.QueryContext(ctx, searchTipoClientes, arg.CONCAT, arg.CONCAT_2, arg.CONCAT_3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tipocliente
	for rows.Next() {
		var i Tipocliente
		if err := rows.Scan(
			&i.Idtipocliente,
			&i.Nombretipoc,
			&i.Descripcion,
			&i.Descuentobase,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleTipoClienteEstado = `-- name: ToggleTipoClienteEstado :execresult
UPDATE tipoCliente
SET estado = NOT estado
WHERE idTipoCliente = ?
`

func (q *Queries) ToggleTipoClienteEstado(ctx context.Context, idtipocliente int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, toggleTipoClienteEstado, idtipocliente)
}

const updateTipoCliente = `-- name: UpdateTipoCliente :execresult
UPDATE tipoCliente
SET
    nombreTipoC = ?,
    descripcion = ?,
    descuentoBase = ?,
    estado = ?
WHERE idTipoCliente = ?
`

type UpdateTipoClienteParams struct {
	Nombretipoc   string          `json:"nombretipoc"`
	Descripcion   string          `json:"descripcion"`
	Descuentobase decimal.Decimal `json:"descuentobase"`
	Estado        int8            `json:"estado"`
	Idtipocliente int32           `json:"idtipocliente"`
}

func (q *Queries) UpdateTipoCliente(ctx context.Context, arg UpdateTipoClienteParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTipoCliente,
		arg.Nombretipoc,
		arg.Descripcion,
		arg.Descuentobase,
		arg.Estado,
		arg.Idtipocliente,
	)
}
