// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dto

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, email, password, role, image)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Role     sql.NullString `json:"role"`
	Image    sql.NullString `json:"image"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.Image,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execresult
UPDATE users
SET estado = NOT estado
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, id)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, role, email, password, image, created_at, updated_at, estado
FROM users
WHERE email = ? AND estado = 1
`

type GetUserByEmailRow struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Role      sql.NullString `json:"role"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Image     sql.NullString `json:"image"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Estado    int8           `json:"estado"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Email,
		&i.Password,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Estado,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, name, role, email, image, created_at, updated_at, estado
FROM users
WHERE estado = 1
`

type GetUsersRow struct {
	ID        int32          `json:"id"`
	Name      string         `json:"name"`
	Role      sql.NullString `json:"role"`
	Email     string         `json:"email"`
	Image     sql.NullString `json:"image"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	Estado    int8           `json:"estado"`
}

func (q *Queries) GetUsers(ctx context.Context) ([]GetUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Email,
			&i.Image,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Estado,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserWithPassword = `-- name: UpdateUserWithPassword :execresult
UPDATE users
SET
    name = ?,
    role = ?,
    email = ?,
    password = ?,
    image = ?,      
    estado = ?
WHERE id = ?
`

type UpdateUserWithPasswordParams struct {
	Name     string         `json:"name"`
	Role     sql.NullString `json:"role"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Image    sql.NullString `json:"image"`
	Estado   int8           `json:"estado"`
	ID       int32          `json:"id"`
}

func (q *Queries) UpdateUserWithPassword(ctx context.Context, arg UpdateUserWithPasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserWithPassword,
		arg.Name,
		arg.Role,
		arg.Email,
		arg.Password,
		arg.Image,
		arg.Estado,
		arg.ID,
	)
}

const updateUserWithoutPassword = `-- name: UpdateUserWithoutPassword :execresult
UPDATE users
SET
    name = ?,
    role = ?,
    email = ?,
    image = ?,      
    estado = ?
WHERE id = ?
`

type UpdateUserWithoutPasswordParams struct {
	Name   string         `json:"name"`
	Role   sql.NullString `json:"role"`
	Email  string         `json:"email"`
	Image  sql.NullString `json:"image"`
	Estado int8           `json:"estado"`
	ID     int32          `json:"id"`
}

func (q *Queries) UpdateUserWithoutPassword(ctx context.Context, arg UpdateUserWithoutPasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserWithoutPassword,
		arg.Name,
		arg.Role,
		arg.Email,
		arg.Image,
		arg.Estado,
		arg.ID,
	)
}
